#!/bin/bash
# 
# CopyRight 2012 Allan Psicobyte (psicobyte@gmail.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.


if [[ $1 ]]; then
	URI=$1

	if [[ $2 ]] && [[ $2 =~ ^[0-9]+$ ]]; then
                if [[ $3 ]]; then
			if [[ $3 =~ ^[0-9]+$ ]]; then
                        	Inicio=$2
                        	Fin=$3
				if [[ $4 ]]; then
					Extension=$4
				else
					Extension=""
				fi
			else
				Inicio=1
                        	Fin=$2
				Extension=$3
			fi
                else
				Inicio=1
                        	Fin=$2
				Extension=""
                fi

		for i in $(eval echo "{$Inicio..$Fin}"); do
			#echo $i
			wget --referer $URI$i$Extension $URI$i$Extension
		done

        else
		echo "no ha indicado un rango"
		echo $2
	fi
else
	echo "USO: wcomic URL PagInicial PagFinal extension"
	echo "ejemplo: wcomic http://direcion.com/dir/arch 1 17 .jpg"
fi











